module.exports.output = 
[
  '.. my-step-id',
  'A. Connect to Your MongoDB Realm App',
  '',
  'To get the app working with your backend, you first need to add your Realm App ',
  'ID to the config.js file. The config.js module exports a single property, ',
  'realmAppId, which is currently set to “TODO”:',
  '',
  '.. code-block:: js',
  '\t',
  '\texports.realmAppId = "TODO";',
  '\t/* I\'m putting in a code-block comment here.',
  '\tThis should be included in the START ONLY */',
  '\t/* ',
  '\tHere\'s another comment for start only!',
  '\t*/',
  '\tlet shouldBeInStartAndFinalCode;',
  '\t// This comment should be in all outputs',
  '',
  '',
  'Change this value to your Realm App ID. ',
  '',
  '.. note::',
  '',
  '   To learn how to find your MongoDB Realm ``appId``, read the :doc:`Find',
  '   Your App Id </get-started/find-your-app-id>` doc.',
  '',
  'Once you have made that change, you now need to complete the code needed to ',
  'open a {+realm+}. In ``index.js``, find the ``openRealm`` function. It will look ',
  'like this:',
  '',
  '.. code-block:: js',
  '\temphasize_lines : 1,5',
  '\tline_numbers : false',
  '\t',
  '\tlet foo = "this line should be in both starter and final"',
  '\tlet bazzle = "this line should be in the starter, but not final"',
  '',
  'Replace the ``TODO`` line with a line of code that opens a {+realm+} and assigns ',
  'it to the ``realm`` property:',
  '',
  '.. code-block:: js',
  '\temphasize_lines : 1-3',
  '\tline_numbers : true',
  '\t',
  '\tlet foo = "this line should be in both starter and final"',
  '\tlet bar = "this line should be in the final code but not starter"',
  '',
  '',
  'At this point, your app is pointing to your backend and opens a connection ',
  'to it when you start the app. However, users cannot yet log in, so let\'s update ',
  'that code next.',
  '',
  '',
  '#. Now it\'s Time to Dance',
  '',
  'I\'m step 2. That\'s cool, right?',
  'I\'m using the default property of the step-start',
  'rather than passing in an object. That makes me',
  'cooler than the previous step.',
  '',
  '',
  '',
 ]

module.exports.codeBlocks = [
  [
    'let foo = "this line should be in both starter and final"',
    'let bazzle = "this line should be in the starter, but not final"'
  ],[
   'exports.realmAppId = "TODO";',
   '/* I\'m putting in a code-block comment here.',
   'This should be included in the START ONLY */',
   '/* ',
   'Here\'s another comment for start only!',
   '*/',
   'let shouldBeInStartAndFinalCode;',
   '// This comment should be in all outputs',
  ],
  [
    'let foo = "this line should be in both starter and final"',
    'let bar = "this line should be in the final code but not starter"'
  ],
  [
    'exports.realmAppId = "mytutorialapp-qwe";',
    'let shouldBeInStartAndFinalCode;',
    '// This comment should be in all outputs'
  ]
]