name: Test docs deployment

on:
  pull_request:
    # only run on not main branch to test
    # it's not nec to run on main b.c this same flow occurs in the deploy action
    # for main.
    branches-ignore: [main]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm
      - name: Test build
        working-directory: docs
        run: |
          npm ci
          npm run build
